### PR TITLE
Image and counters

### PR DESCRIPTION
**Pull request by datdenkikniet**
Reduce the featureset of `image` so we don't draw in the other million dependencies it has to support jpeg, svg, and other image formats (that we don't use).

Remove a layer of decoding logic. Not entirely certain if this actually changes much (it's been a while since I made that change...). AFAICT it doesn't change the speed of the program, but since `Lines` is generic over `AsyncRead + AsyncWrite` it makes the implementation a bit easier to maintain, and it should still work over generic `Client`s that implement these traits.

Only update the atomic pixels value after processing each "command frame" so that that update doesn't act as so much of a synchronization barrier anymore in multithreaded contexts

### CODE REVIEW

**Comment by timvisee** [comment]
It seems these changes introduce an error. The server gets stuck shortly after a client connects.

I see this behavior with multiple pixelflut clients.

Any idea what is causing this? Possibly a faulty merge?

**Comment by datdenkikniet** [comment]
Ah, that's not great. What client are you using that exhibits that behaviour? I've probably introduced some incorrect logic somewhere

**Comment by datdenkikniet** [comment]
The server is now actually sending newlines in response messages again. It should now work

**Comment by timvisee** [comment]
> The server is now actually sending newlines in response messages again. It should now work

Fantastic!

**Comment by datdenkikniet** [comment]
I assume it works again?

Please hold off on merging btw, I'm gonna write some small tests so that easy stuff like this isn't overlooked so quickly xD

**Review by timvisee — APPROVED** [review]

**Comment by timvisee** [comment]
> I assume it works again, then? Sweet!

Just tested. It does!

> Please hold off on merging at any rate, I'm gonna write some small tests so that easy stuff like

Alright! Please let me know when this can be merged.

**Comment by datdenkikniet** [comment]
Alright, should be good now! We'll probably want to add some github actions CI in the future to actually run the test, but that's for another day

**Review by timvisee — APPROVED** [review]

**Comment by timvisee** [comment]
LGTM. Merged!

**Pull request merged**
