### PR TITLE
Experiment: Use atomics and mUtaBle borrows for great good

### PR DESCRIPTION
**Pull request by datdenkikniet**
Mostly a PR to see if this would work, and what the performance impact would be.

This PR converts `Pixmap` so that it uses `Vec<AtomicU32>` as storage, and requires exclusive access for the `as_bytes` function.

This way, we completely remove (for this application inconsequential) the currently present UB, because the slice that is returned from `as_bytes` now prevents any other accesses to occur during its lifetime, which means that the `mut ^ immut` access invariant that rust requires is upheld.

(Very manual so not particularly precise) observations so far:
1. Non-binary commands (`PX 15 15 FFFFFFFF`) are ~25% slower (13.0 MP/s -> 10.2 MP/s)
2. 8 concurrent non-binary command runners are ~15% slower (65.0 MP/s -> 56.1 MP/s)
3. Binary commands 2% slower (52.8 MP/s -> 51.8 MP/s
4. 8 concurrent binary command runners are 3% slower (165 MP/s -> 160 MP/s)

I  thought that the "problem" with the non-binary commands is that they're larger (byte-length wise), causing fewer of them fit into the RX buffer, which in turn means that a read lock has to be acquired more often for a specific amount of pixels than in the binary command case. However, that doesn't seem to hold: increasing `BUF_SIZE` actually makes the program slightly slower. Perhaps the amount of and order of lock contention is "just right" in the case of 8 connections?

### CODE REVIEW

**Comment by timvisee** [comment]
Interesting findings, thanks for giving this a try!

I'd just want to add the following, on the original `Pixmap` implementation:

A single pixel is represented as `u32`, with 4x8-bit color channels. The thing is that `u32` assignments on x86, if aligned (`#[repr(align(4))]`), are already atomic[^1]. That means that on that architecture, using `AtomicU32` is obsolete. 

In situations where this may not be the case, any pixel color _glitches_ are _accepted_ behavior to keep things very fast, as we aren't doing important things with pixel data that would require guaranteed atomicity. That was the idea of the original `Pixmap` implementation.

I actually believe that other architectures behave very similarly, but I haven't done deep research on it.

I don't have super good understanding of low level stuff like this, so please correct me if I'm wrong on this or if I'm missing something.

[^1]: https://stackoverflow.com/questions/36624881/why-is-integer-assignment-on-a-naturally-aligned-variable-atomic-on-x86

**Comment by timvisee** [comment]
Marking this as draft for now. Feel free to undraft it at any time.

**Comment by datdenkikniet** [comment]
Ah yes, thanks! I was trying to figure out how to do that...

I agree that none of the "problems" that this PR would fix actually impact the performance or usability of the program.

AFAIK, what you're saying is very true, and  The assembly for `AtomicU32::load` with `Ordering::Relaxed` is (almost always) the same as a normal `let x = some_u32;`, same for store.

The thing that using Atomics and the `&mut self` requirement  actually fixes in this case is the overall soundness of the program from the language's POV (see also: [Behavior considered undefined](https://doc.rust-lang.org/reference/behavior-considered-undefined.html): 
1. We remove the UB in `PixelMap::write_pixel_raw`, since writing to an `*mut _` created from an immutable reference is UB
2. We remove the UB in `PixelMap::as_bytes`. Before, we were giving the caller an immutable reference to data that might mutate while the caller holds that reference. Before, you could technically do this by doing something like
```rust
// assuming `map` a default PixMap
let bytes = map.as_bytes();
let first_pixel = bytes[0];
// Now we create some UB: we mutate the data contained within `bytes` (indirectly)
map.set_pixel(0, 0, Color::new(1));
 // This assert could fail, or the compiler could optimize it out all together, or not. Whatever it does,
// we don't get any guarantees.
assert_eq!(bytes[0], first_pixel);
```

**Comment by datdenkikniet** [comment]
I have re-done this a bit more now, and now all the UB is gone without any impact to performance!

Instead of doing this whacky thing with an RwLock, we can just clone the image data if we need to get mutable access to it :)

Tested it now and everything seems to be running at exactly the same speed as before! Actually ready for merge this time around :P

**Review by timvisee — APPROVED** [review]
Thanks for pushing this to the finish line!

**Pull request merged**
